# apply this resource to activate a passive configuration
# this resource can be applied after the restore-acm-passive configuration was applied on this hub
# after this resource is applied, all restored managed clusters 
# will resume connection on the current hub; hive clusters will automatically switch to this cluster

# cleanupBeforeRestore - required, asks to clean up cluster before applying restore
# valid options : 
# CleanupRestored - clean up only resources created by a previous acm restore
# CleanupAll - clean up all resources defined by the acm backups IncludedResources spec
#              even if they were not created as a result of a restore operation
#              Use this option with caution as this could cleanup resources on the hub
#              created by the user, that should be kept even if they are not in the restored resources
# None : don't clean up anything, just apply the restore

apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-acm-passive-activate
spec:
  cleanupBeforeRestore: CleanupRestored
  veleroManagedClustersBackupName: latest
  veleroCredentialsBackupName: skip
  veleroResourcesBackupName: skip