#
# This policy reports on any configuration errors for the application backup or restore scenarios.
# Install this policy on the hub, after you install the oadp-hdr-app-install policy
#
# Note that it is set to inform as it only validates the installed configuration
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oadp-hdr-app-install-report
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-app-oadp-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  annotations:
                    repository: https://github.com/openshift/oadp-operator
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: Running
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-app-velero-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app.kubernetes.io/name: velero
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: Running
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-app-dpa-complete
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: oadp.openshift.io/v1alpha1
                kind: DataProtectionApplication
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "dpaName" hub}}'
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  conditions:
                    - reason: Complete
                      type: Reconciled
          remediationAction: infrom
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-storage-location-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: BackupStorageLocation
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "dpaName" hub}}-1'
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: Available                
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-error
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                  labels:
                    velero.io/schedule-name: acm-pv-{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}-{{ fromClusterClaim "name" }}
                status:
                  phase: Error                
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-failed-validation
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                  labels:
                    velero.io/schedule-name: acm-pv-{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}-{{ fromClusterClaim "name" }}
                status:
                  phase: FailedValidation                
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-partially-failed
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                  labels:
                    velero.io/schedule-name: acm-pv-{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}-{{ fromClusterClaim "name" }}
                status:
                  phase: PartiallyFailed                
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-in-progress
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                labels:
                  velero.io/schedule-name: acm-pv-{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}-{{ fromClusterClaim "name" }}
                status:
                  phase: InProgress                
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-no-status
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                labels:
                  velero.io/schedule-name: acm-pv-{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}-{{ fromClusterClaim "name" }}
                status:
                  phase: ''                                                            
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-failed
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Restore
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: Failed                                                            
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-failed
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Restore
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: PartiallyFailed                                                            
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-in-progress
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Restore
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: InProgress                                                            
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-no-status
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Restore
                metadata:
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                status:
                  phase: ''                                                            
          remediationAction: inform
          severity: low
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: oadp-hdr-app-install-report-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: acm-pv-dr-install
        operator: In
        values:
          - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oadp-hdr-app-install-report-placement-binding
  namespace: default
placementRef:
  name: oadp-hdr-app-install-report-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: oadp-hdr-app-install-report
    apiGroup: policy.open-cluster-management.io
    kind: Policy