#
# This policy creates a velero schedule to all managed clusters with a label "acm-pv-dr=backup".
# The schedule is used to backup applications resources and PVs.
# The schedule uses the `backup.nsToBackup` hdr-app-configmap property to specify the namespaces for the applications to backup. 
# 
# Create this policy on the hub managing clusters where you want to create stateful applications backups, 
# and after you create the oadp-hdr-app-install and oadp-hdr-app-validation policies.
#
# Both policies, oadp-hdr-app-backup and oadp-hdr-app-restore can be installed on the same hub,
# if this hub manages clusters where applications need to be backed up or restored. 
#
# Note that a managed cluster can either be a backup target or a restore target, not both at the same time.
#
# - If the managed cluster (or hub) has the label "acm-pv-dr=backup" then the oadp-hdr-app-backup policy 
# is propagated to this cluster for an application backup schedule. This cluster produces applications backups.
# Make sure the hdr-app-configmap's backup schedule resource settings are properly set before applying this policy.
#
# - If the managed cluster (or hub) has the label "acm-pv-dr=restore" then the oadp-hdr-app-restore policy 
# is propagated to this cluster for backup restore operation. This cluster restores applications backup.
# Make sure the hdr-app-configmap's restore resource settings are properly set before applying this policy.
#
# Note that it is set to enforce by default.
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oadp-hdr-app-backup
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-ns-backup
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-schedule-resource
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Schedule
                metadata:
                  name: 'acm-pv-{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}-{{ fromClusterClaim "name" }}'
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                  labels:
                    cluster-id: '{{ fromClusterClaim "id.openshift.io" }}'
                    cluster-name: '{{ fromClusterClaim "name" }}'
                spec:
                  schedule: '{{hub fromConfigMap "" "hdr-app-configmap" "backup.schedule" hub}}' 
                  template:
                    volumeSnapshotLocations:
                      - '{{hub fromConfigMap "" "hdr-app-configmap" "backup.volumeSnapshotLocation" hub}}' 
                    snapshotVolumes: true
                    includedNamespaces: '{{hub fromConfigMap "" "hdr-app-configmap" "backup.nsToBackup" | toLiteral hub}}' 
                    ttl: '{{hub fromConfigMap "" "hdr-app-configmap" "backup.ttl" hub}}'  
          pruneObjectBehavior: DeleteIfCreated             
          remediationAction: enforce
          severity: high
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: oadp-hdr-app-backup-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: acm-pv-dr
        operator: In
        values:
          - backup
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oadp-hdr-app-backup-placement-binding
  namespace: default
placementRef:
  name: oadp-hdr-app-backup-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: oadp-hdr-app-backup
    apiGroup: policy.open-cluster-management.io
    kind: Policy